"""
A helper script to test out what social previews look like.
I should remove this when I'm happy with the result.
"""
# %load_ext autoreload
# %autoreload 2

from sphinx_social_previews.card import create_social_card_objects
import random
from pathlib import Path

# Dummy lorem text
lorem = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
""".split()  # noqa

# Create basic figures
fig, txtsite, txtpage, txtdesc, txturl = create_social_card_objects(
    # image="docs/_static/logo-wide.png",
    image="docs/_static/logo.png",
    image_mini="sphinx_social_previews/_static/logo-mini.png",
)

# These are roughly the max characters we enforce
# Leaving here for texting
MAX_CHAR_PAGETITLE = 70
MAX_CHAR_DESCRIPTION = 175

for perm in range(10):
    # Fixed site title since this is not autogenerated
    txtsite.set_text("Chris Holdgraf's website")

    # Create dummy text description and pagetitle for this iteration
    random.shuffle(lorem)
    title = " ".join(lorem[:100])
    title = title[: MAX_CHAR_PAGETITLE - 3] + "..."
    txtpage.set_text(title)

    random.shuffle(lorem)
    desc = " ".join(lorem[:100])
    desc = desc[: MAX_CHAR_DESCRIPTION - 3] + "..."
    txtdesc.set_text(desc)

    txturl.set_text("chrisholdgraf.com")
    Path("tmp").mkdir(exist_ok=True)
    fig.savefig(f"./tmp/num_{perm}.png", facecolor="w")
